name: Report Commit to Discord

on:
  push:
    branches:
      - "*"

jobs:
  report-commit-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "content": "🚀 **New Commit Alert!**",
              "embeds": [
                {
                  "title": "${{ github.event.head_commit.message }}",
                  "description": "A new commit has been pushed to **${{ github.repository }}**.",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Commit Author",
                      "value": "${{ github.event.head_commit.author.name }}"
                    },
                    {
                      "name": "Branch",
                      "value": "${{ github.ref }}"
                    },
                    {
                      "name": "View Commit",
                      "value": "[Click here to view the commit](${{ github.event.head_commit.url }})"
                    }
                  ],
                  "footer": {
                    "text": "Commit ID: ${{ github.sha }}"
                  },
                  "timestamp": "${{ github.event.head_commit.timestamp }}"
                }
              ],
              "attachments": []
            }
