name: Report Commit to Discord

on:
  push:
    branches:
      - "*"

jobs:
  report-commit-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up commit info
        run: |
          echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "FIRST_LINE=$(echo $COMMIT_MESSAGE | head -n 1)" >> $GITHUB_ENV
          ISSUE_ID=$(echo $COMMIT_MESSAGE | grep -o 'ANT-[0-9]\+')
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "content": "🚀 **New Commit Alert!**",
              "embeds": [
                {
                  "title": "$FIRST_LINE",
                  "description": "A new commit has been pushed to **${{ github.repository }}**. \n\n**Description:**\n$COMMIT_MESSAGE",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Commit Author",
                      "value": "${{ github.event.head_commit.author.name }}"
                    },
                    {
                      "name": "Branch",
                      "value": "${{ github.ref }}"
                    },
                    {
                      "name": "View Commit",
                      "value": "[Click here to view the commit](${{ github.event.head_commit.url }})"
                    },
                    ${
                      env.ISSUE_ID ? 
                      `{
                        "name": "Linear Issue",
                        "value": "[View Issue](https://linear.app/antoniobfm/issue/$ISSUE_ID)" # Change antoniobfm to your workspace name
                      },` : ''
                    }
                  ],
                  "footer": {
                    "text": "Commit ID: ${{ github.sha }}"
                  },
                  "timestamp": "${{ github.event.head_commit.timestamp }}"
                }
              ],
              "attachments": []
            }
