name: Report Commit to Discord

on:
  push:
    branches:
      - "*"

jobs:
  report-commit-to-discord:
    runs-on: ubuntu-latest
    environment:
      name: Semantic
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "content": null,
              "embeds": [
                {
                  "title": "Novo Commit",
                  "description": "Discohook has a bot as well, it`s not strictly required to send messages it may be helpful to have it ready.",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Getting special formatting for mentions, channels, and emoji",
                      "value": "The **/format** command of the bot can give you special formatting for use in Discord messages that lets you create mentions, tag channels, or use emoji ready to paste into the editor!\n\nThere are [manual ways](https://discord.dev/reference#message-formatting) of doing this, but it`s very error prone. The bot will make sure you`ll always get the right formatting for your needs."
                    },
                    {
                      "name": "Creating reaction roles",
                      "value": "You can manage reaction roles with the bot using the **/reaction-role** command.\n\nThe set-up process is very intuitive: type out **/reaction-role create**, paste a message link, select an emoji, and pick a role. Hit enter and you're done, your members can now react to any of your messages to pick their roles."
                    },
                    {
                      "name": "Recover Discohook messages from your server",
                      "value": "It can also restore any message sent in your Discord server for you via the apps menu.\n\nTo get started, right-click or long-press on any message in your server, press on apps, and then press **Restore to Discohook**. It`ll send you a link that leads to the editor page containing the message you selected!"
                    },
                    {
                      "name": "Other features",
                      "value": "Discohook can also grab images from profile pictures or emoji, manage your webhooks, and more. Invite the bot and use **/help** to learn about all the bot offers!"
                    }
                  ]
                }
              ],
              "attachments": []
            }
