name: Report Commit to Discord

on:
  push:
    branches:
      - "*"

jobs:
  report-commit-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Linear Issue ID
        id: linear
        run: |
          echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" > $GITHUB_ENV
          ISSUE_ID=$(echo $COMMIT_MESSAGE | grep -o 'ANT-[0-9]\+') # Change PRO to your project prefix
          echo "::set-output name=issue_id::$ISSUE_ID"

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "content": "🚀 **New Commit Alert!**",
              "embeds": [
                {
                  "title": "${{ github.event.head_commit.message.split('\n')[0] }}",
                  "description": "A new commit has been pushed to **${{ github.repository }}**. \n\n**Description:**\n${{ github.event.head_commit.message }}",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Commit Author",
                      "value": "${{ github.event.head_commit.author.name }}"
                    },
                    {
                      "name": "Branch",
                      "value": "${{ github.ref }}"
                    },
                    {
                      "name": "View Commit",
                      "value": "[Click here to view the commit](${{ github.event.head_commit.url }})"
                    },
                    ${
                      steps.linear.outputs.issue_id ? 
                      `{
                        "name": "Linear Issue",
                        "value": "[View Issue](https://linear.app/antoniobfm/issue/${{ steps.linear.outputs.issue_id }})" # Change antoniobfm to your workspace name
                      },` : ''
                    }
                  ],
                  "footer": {
                    "text": "Commit ID: ${{ github.sha }}"
                  },
                  "timestamp": "${{ github.event.head_commit.timestamp }}"
                }
              ],
              "attachments": []
            }
