name: Report Commit to Discord

on:
  push:
    branches:
      - "*"

jobs:
  report-commit-to-discord:
    runs-on: ubuntu-latest
    environment:
      name: Semantic
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Linear ID
        run: |
          # Extract the Linear ID from the commit message and set it as an environment variable
          LINEAR_ID=$(echo "${{ github.event.head_commit.message }}" | head -n 1 | grep -o 'ANT-[0-9]\+' || true)
          echo "LINEAR_ID=$LINEAR_ID" >> $GITHUB_ENV

        shell: /usr/bin/bash -e {0}

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "content": "🚀 **New Commit Alert!** 🚀",
              "embeds": [
                {
                  "title": "${{ github.event.head_commit.message }}",
                  "description": "A new commit has been pushed to **${{ github.repository }}**.",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Commit Author",
                      "value": "${{ github.event.head_commit.author.name }}"
                    },
                    {
                      "name": "Branch",
                      "value": "${{ github.ref }}"
                    },
                    {
                      "name": "View Commit",
                      "value": "[Click here to view the commit](${{ github.event.head_commit.url }})"
                    },
                    {
                      "name": "View Linear Issue",
                      # Change antoniobfm to your Linear workspace name
                      "value": "[View Linear Issue](https://linear.app/antoniobfm/issue/${{ env.LINEAR_ID }})",
                      "inline": true
                    }
                  ],
                  "footer": {
                    "text": "Commit ID: ${{ github.sha }}"
                  },
                  "timestamp": "${{ github.event.head_commit.timestamp }}"
                }
              ],
              "attachments": []
            }
